/*
 *  Copyright (c) 2023, 2024, Oracle and/or its affiliates. All rights reserved.
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  This code is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 2 only, as
 *  published by the Free Software Foundation.  Oracle designates this
 *  particular file as subject to the "Classpath" exception as provided
 *  by Oracle in the LICENSE file that accompanied this code.
 *
 *  This code is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  version 2 for more details (a copy is included in the LICENSE file that
 *  accompanied this code).
 *
 *  You should have received a copy of the GNU General Public License version
 *  2 along with this work; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *   Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 *  or visit www.oracle.com if you need additional information or have any
 *  questions.
 */

// Generated by jextract

package org.openjdk.jextract.clang.libclang;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     const void *ASTNode;
 *     CXTranslationUnit TranslationUnit;
 * }
 * }
 */
public class CXComment {

    CXComment() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Index_h.C_POINTER.withName("ASTNode"),
        Index_h.C_POINTER.withName("TranslationUnit")
    ).withName("$anon$36:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout ASTNode$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ASTNode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *ASTNode
     * }
     */
    public static final AddressLayout ASTNode$layout() {
        return ASTNode$LAYOUT;
    }

    private static final long ASTNode$OFFSET = $LAYOUT.byteOffset(groupElement("ASTNode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *ASTNode
     * }
     */
    public static final long ASTNode$offset() {
        return ASTNode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *ASTNode
     * }
     */
    public static MemorySegment ASTNode(MemorySegment struct) {
        return struct.get(ASTNode$LAYOUT, ASTNode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *ASTNode
     * }
     */
    public static void ASTNode(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ASTNode$LAYOUT, ASTNode$OFFSET, fieldValue);
    }

    private static final AddressLayout TranslationUnit$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("TranslationUnit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * CXTranslationUnit TranslationUnit
     * }
     */
    public static final AddressLayout TranslationUnit$layout() {
        return TranslationUnit$LAYOUT;
    }

    private static final long TranslationUnit$OFFSET = $LAYOUT.byteOffset(groupElement("TranslationUnit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * CXTranslationUnit TranslationUnit
     * }
     */
    public static final long TranslationUnit$offset() {
        return TranslationUnit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * CXTranslationUnit TranslationUnit
     * }
     */
    public static MemorySegment TranslationUnit(MemorySegment struct) {
        return struct.get(TranslationUnit$LAYOUT, TranslationUnit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * CXTranslationUnit TranslationUnit
     * }
     */
    public static void TranslationUnit(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(TranslationUnit$LAYOUT, TranslationUnit$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

